### PR TITLE
Add check to make sure .appear is only called once when element stays in view.

### PR DESCRIPTION
**Pull request by jer2665**
I need something to fire a settimeout when item appears, but 0.3.6 fires that every time you scroll with it in view too. This keeps track of if the element is in view and has appeared, and only triggers appear once, until the element disappears.

### CODE REVIEW

**Comment by jer2665** [comment]
I'm working on upgrading my site to jquery3 and the jquerymigrate plugin is complaining on...
JQMIGRATE: jQuery.expr[':'] is deprecated; use jQuery.expr.pseudos

This just uses the new way to handle pseudos

**Comment by jvitoroc** [comment]
Your commit is not working

**Comment by jer2665** [comment]
Can you be more specific? I just did a test and it's working fine for me. Here are two codepens...

Original jquery.appear.js
https://codepen.io/jer2665/pen/QMmbzN/

My changes to script
https://codepen.io/jer2665/pen/yoKNGg/

**Comment by jvitoroc** [comment]
I was using jquery 3, maybe that is the problem. Fork this project and make your version

**Comment by jer2665** [comment]
Codepen is using jquery3 as well, according to $.fn.jquery it's 3.2.1 as of my just checking.

**Comment by Mohsen-Khakbiz** [comment]
it's working pretty fine for me. appreciate it

**Pull request closed without merging**
