### PR TITLE
Fire the check function on beginning.

### PR DESCRIPTION
**Pull request by danielhusar**
Fire the check function on beginning so events for visible elements are executed immediately.

Issue #25 is related to this.

### CODE REVIEW

**Comment by user24** [comment]
+1

**Comment by inferusvv** [comment]
+1

**Comment by redpik** [comment]
this snippet works for me:

`
	$(window).load(function() {
		$.force_appear();
	});
`

**Comment by danielhusar** [comment]
Closing for inactivity.

**Pull request closed without merging**
